In [2]:
import os
import numpy as np
import pandas as pd
import dash
from dash import dcc, html
from dash.dependencies import Input, Output
import dash_bootstrap_components as dbc
import plotly.express as px
import plotly.graph_objects as go
os.getcwd()

'/Users/kristiinajoon/Documents/Projects/KeM/veebirakendus_demo'

In [3]:
# create plot(s)

# get data
df = pd.read_csv("energeetika.csv", na_values='', keep_default_na=True) # identify NaN values as empty space, don't import NaN values to dataframe
df = df.drop(df.columns[5:], axis=1) # here defo better way, remove unnecessary columns
df = df.drop(df.columns[1], axis=1) # remove column
df = df.drop(df.columns[2], axis=1)
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_').str.replace('(', '').str.replace(')', '') # clean out names

# initialise plots
fig_protsent = go.Figure()
fig_kogu = go.Figure()
df['muu_heide'] = (df['koguheide_maakasutuseta_kt_co2_ekv'] - df['energeetika_kt_co2_ekv'])
df['en_protsent'] = (df['energeetika_kt_co2_ekv'] / df['koguheide_maakasutuseta_kt_co2_ekv'] * 100)
df['muu_protsent'] = (100 - df['en_protsent'])

# test using a set year range
years=[1995,2010]
dff = df.copy()                         # make copy of dataframe
dff = dff[dff['aasta'].between(years[0], years[1])]
dff
# # plot
# fig_protsent = px.bar(df,                   # suhteline heide, graafik protsentides
#              x='aasta',
#              y=['en_protsent','muu_protsent'],
#              barmode='stack',
#              color_discrete_map={
#              'en_protsent': '#440154',
#              'muu_protsent': '#5ec962'}, 
#              opacity=0.7)
# fig_protsent.update_layout(                          # add range slider, comment out if want to use a dash slider
#     xaxis=dict(
#         rangeselector=dict(
#             buttons=list([                           # add buttons for 5 and 10 years, give min range to slider, manipulate slider??
#                 # dict(count=5,
#                 #      label="5 aastat",
#                 #      step=1,
#                 #      stepmode="backward"),
#                 # dict(count=10,
#                 #      label="10 aastat",
#                 #      step=1,
#                 #      stepmode="backward"),
#                 dict(count=31,
#                      label="kõik",
#                      step="all")
#             ])
#         ),
#         rangeslider=dict(
#             visible=True
#         ),
#         type="date"
#     )
# )

# fig_kogu = px.bar(df,                       # absoluutne heide, graafik kt CO2 ekv
            #  x='aasta',
            #  y=['energeetika_kt_co2_ekv','muu_heide'],
            #  barmode='stack',
            #  color_discrete_map={
            #  'energeetika_kt_co2_ekv': '#440154',
            #  'muu_heide': '#5ec962'}, 
            #  opacity=0.7)

# test if wish
# fig_protsent.show()
# fig_kogu.show()

/var/folders/39/_jkw8gcx2_l0kj6z6ksdt_440000gn/T/ipykernel_3121/233682942.py:8: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_').str.replace('(', '').str.replace(')', '') # clean out names

,aasta,energeetika_kt_co2_ekv,koguheide_maakasutuseta_kt_co2_ekv,muu_heide,en_protsent,muu_protsent
5,1995,17867.11,20273.77,2406.66,88.129194,11.870806
6,1996,18822.54,21180.71,2358.17,88.866426,11.133574
7,1997,18284.56,20759.07,2474.51,88.079861,11.920139
8,1998,16454.02,19021.44,2567.42,86.502494,13.497506
9,1999,15512.13,17850.09,2337.96,86.902251,13.097749
10,2000,15106.21,17495.87,2389.66,86.341577,13.658423
11,2001,15489.60,17933.88,2444.28,86.370601,13.629399
12,2002,15147.82,17342.07,2194.25,87.347243,12.652757
13,2003,17004.22,19284.11,2279.89,88.177365,11.822635
14,2004,17026.36,19482.32,2455.96,87.393904,12.606096
15,2005,16835.65,19257.08,2421.43,87.425768,12.574232
16,2006,16155.64,18598.88,2443.24,86.863510,13.136490
17,2007,19525.00,22206.85,2681.85,87.923321,12.076679
18,2008,17351.51,20083.66,2732.15,86.396155,13.603845
19,2009,14455.50,16661.56,2206.06,86.759583,13.240417
20,2010,18935.07,21218.19,2283.12,89.239798,10.760202

In [4]:
# create web application
app = dash.Dash(__name__, external_stylesheets=[dbc.themes.FLATLY]) 
# capitalise dbc theme
# always declare a theme!!!

markdown_top = '''
# Big heading
### Small heading

Just wanted to make sure this is centred.
'''

markdown_body = '''
Here's lots of other text that it really really long. 
kshaskjjshflasihflasifslf;iosdhglsuhgklsjdbgsdbfgsuhf.
erkrgerhbgmerhgkerughrekgjbermgbkejrbgkergkeuhrgkuehrgkuebg.
ergkjbrekbgekrjbgkejbrgkejrbgkebrjgkejrbgkrejbgkejbg.
erkbgkejrgbkejrbgkejbrgkjberkgberkgbkerjbgkerbjgkjerbg.

This text should be left-aligned but not take up the 
whole space. Trying to use a container for this. 

Regular paragraph text:
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
** Double asterisk makes text bold **
*Single asterisk makes texts italics*
create `inline code` with a back tick around the code
Create links like `[``links``]``(http://commonmark.org/help)` but remove the back ticks
You can make lists too!
* item 1
* item 2
* item 3
1. item 1
2. item 2
3. item 3
'''

app.layout = html.Div(children=[
    html.Div([
        dcc.Markdown(children=markdown_top, style={'text-align': 'center'})
        ]),  

    dbc.Container([                         # MUST declare a bootsrap theme AT TOP or dbc won't work
        html.Div([
        dcc.Markdown(children=markdown_body),
        dcc.Dropdown(
            id='dropdown',
            options=[
                {'label': 'suhteline heide', 'value': 'protsent'},
                {'label': 'koguheide', 'value': 'kogu'},
                    ],
            value='protsent',
            style={"width": "30%"}),
        ])   
    ]),
])

app.run_server(debug=True, use_reloader=False)

Dash is running on http://127.0.0.1:8050/

 * Serving Flask app '__main__' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on